
const buttonMenuTarget= [
    {
        id:0,
        eventClick:0,
        avaiableClass:true,
        disabledButton:false,
        titleButton:"Somas com unidades",
        ScreenGameAble:false,
        ScreenSettings:{
            libera_exercicio:1,
            title:"Somar Unidades",
            primeira_variavel_numerica:10,
            segundo_limite:0,
            terceiro_limite:0,
            first:25,
            second:30,
            third:35,
            fourth:45,
            fifth:75,
            signal:'+',
            call_reset:"0",
            polivariaveis:1
        }
    },
    {
        id:1,
        eventClick:1,
        avaiableClass:false,
        disabledButton:true,
        titleButton:"Soma Dezenas",
        ScreenGameAble:false,
        ScreenSettings:{
            libera_exercicio:2,
            title:"Somar Dezenas",
            primeira_variavel_numerica:40,
            segundo_limite:0,
            terceiro_limite:0,
            first:40,
            second:50,
            third:60,
            fourth:65,
            fifth:75,
            signal:'+',
            call_reset:1,
            polivariaveis:1
        }
    },
    { 
        id:2,
        eventClick:2,
        avaiableClass:false,
        disabledButton:true,
        titleButton:"Subtração",
        ScreenGameAble:false,
        ScreenSettings:{
            libera_exercicio:3,
            title:"Subtrair",
            primeira_variavel_numerica:9,
            segundo_limite:20,
            terceiro_limite:10,
            first:40,
            second:50,
            third:60,
            fourth:65,
            fifth:75,
            signal:'-',
            call_reset:"2",
            polivariaveis:2
        }
    },
    {
        id:3,
        eventClick:3,
        avaiableClass:false,
        disabledButton:true,        
        titleButton:"Tabuada 2 Primeira Parte",
        ScreenGameAble:false,
        ScreenSettings:{
            libera_exercicio:4,
            title:"Tabuada do dois",
            primeira_variavel_numerica:2,
            segundo_limite:5,
            terceiro_limite:10,
            first:40,
            second:50,
            third:60,
            fourth:65,
            fifth:75,
            signal:'*',
            call_reset:"3",
            polivariaveis:3
        }
    },
    {  
        id:4,
        eventClick:4,
        avaiableClass:false,
        disabledButton:true,
        titleButton:"Tabuada 2 Segunda Parte",
        ScreenGameAble:false,
        ScreenSettings:{
            libera_exercicio:5,
            title:"Tabuada do dois Segunda parte",
            primeira_variavel_numerica:2,
            segundo_limite:11,
            terceiro_limite:6,
            first:40,
            second:50,
            third:60,
            fourth:65,
            fifth:75,
            signal:'*',
            call_reset:"4",
            polivariaveis:4
        }
    },
     {
         id:5,
        eventClick:5,
        avaiableClass:false,
        disabledButton:true,
        titleButton:"Tabuada 2 Completa",
        ScreenGameAble:false,
        ScreenSettings:{
            libera_exercicio:6,
            title:"Tabuada 2 Completa",
            primeira_variavel_numerica:2,
            segundo_limite:11,
            terceiro_limite:0,
            first:40,
            second:50,
            third:60,
            fourth:65,
            fifth:75,
            signal:'*',
            call_reset:"5",
            polivariaveis:4
        }
    },
    {
        id:6,
        eventClick:6,
        avaiableClass:false,
        disabledButton:true,
        titleButton:"Tabuada 3 Primeira Parte",
        ScreenGameAble:false,
        ScreenSettings:{
            libera_exercicio:7,
            title:"Tabuada 3 Primeira Parte",
            primeira_variavel_numerica:3,
            segundo_limite:5,
            terceiro_limite:10,
            first:40,
            second:50,
            third:60,
            fourth:65,
            fifth:75,
            signal:'*',
            call_reset:"6",
            polivariaveis:3
        }
    },
    {
        id:7,
        eventClick:7,
        avaiableClass:false,
        disabledButton:true,
        titleButton:"Tabuada 3 Segunda Parte",
        ScreenGameAble:false,
        ScreenSettings:{
            libera_exercicio:8,
            title:"abuada 3 Segunda Parte",
            primeira_variavel_numerica:3,
            segundo_limite:11,
            terceiro_limite:6,
            first:40,
            second:50,
            third:60,
            fourth:65,
            fifth:75,
            signal:'*',
            call_reset:"7",
            polivariaveis:4
        }
    },
    {
        id:8,
        eventClick:8,
        avaiableClass:false,
        disabledButton:true,
        titleButton:"Tabuada 3 Completa",
        ScreenGameAble:false,
        ScreenSettings:{
            libera_exercicio:9,
            title:"Tabuada 3 Completa",
            primeira_variavel_numerica:3,
            segundo_limite:11,
            terceiro_limite:0,
            first:40,
            second:50,
            third:60,
            fourth:65,
            fifth:75,
            signal:'*',
            call_reset:"8",
            polivariaveis:4
        }
    },
    {
        id:9,
        eventClick:9,
        avaiableClass:false,
        disabledButton:true,
        titleButton:"Tabuada 4 Primeira Parte",
        ScreenGameAble:false,
        ScreenSettings:{
            libera_exercicio:10,
            title:"Tabuada do quatro",
            primeira_variavel_numerica:4,
            segundo_limite:5,
            terceiro_limite:10,
            first:40,
            second:50,
            third:60,
            fourth:65,
            fifth:75,
            signal:'*',
            call_reset:"9",
            polivariaveis:3
        }
    },
    {
        id:10, 
        eventClick:10,
        avaiableClass:false,
        disabledButton:true,
        titleButton:"Tabuada 4 Segunda Parte",
        ScreenGameAble:false,
        ScreenSettings:{
            libera_exercicio:11,
            title:"STabuada 4 Segunda Parte",
            primeira_variavel_numerica:4,
            segundo_limite:11,
            terceiro_limite:6,
            first:40,
            second:50,
            third:60,
            fourth:65,
            fifth:75,
            signal:'*',
            call_reset:"10",
            polivariaveis:4
        }
    },
    {   id:11,
        eventClick:11,
        avaiableClass:false,
        disabledButton:true,
        titleButton:"Tabuada 4 Completa",
        ScreenGameAble:false,
        ScreenSettings:{
            libera_exercicio:12,
            title:"Tabuada 4 Completa",
            primeira_variavel_numerica:4,
            segundo_limite:11,
            terceiro_limite:0,
            first:40,
            second:50,
            third:60,
            fourth:65,
            fifth:75,
            signal:'*',
            call_reset:"11",
            polivariaveis:4
        }
    },
    {   id:12,
        eventClick:12,
        avaiableClass:false,
        disabledButton:true,
        titleButton:"Soma com Dezenas Segunda parte",
        ScreenGameAble:false,
        ScreenSettings:{
            libera_exercicio:13,
            title:"Soma com Dezenas Segunda parte",
            primeira_variavel_numerica:90,
            segundo_limite:0,
            terceiro_limite:0,
            first:55,
            second:65,
            third:75,
            fourth:90,
            fifth:110,
            signal:'+',
            call_reset:"12",
            polivariaveis:1
        }
    },
    { 
        id:13,
        eventClick:13,
        avaiableClass:false,
        disabledButton:true,
        titleButton:"Subtração Segunda  parte",
        ScreenGameAble:false,
        ScreenSettings:{
            libera_exercicio:14,
            title:"Subtrair Segunda parte",
            primeira_variavel_numerica:9,
            segundo_limite:40,
            terceiro_limite:20,
            first:40,
            second:50,
            third:60,
            fourth:65,
            fifth:75,
            signal:'-',
            call_reset:"13",
            polivariaveis:2
        }
    },
    { 
        id:14,
        eventClick:14,
        avaiableClass:false,
        disabledButton:true,
        titleButton:"Subtração Terceira  parte",
        ScreenGameAble:false,
        ScreenSettings:{
            libera_exercicio:15,
            title:"Subtrair Terceira parte",
            primeira_variavel_numerica:20,
            segundo_limite:40,
            terceiro_limite:25,
            first:40,
            second:50,
            third:60,
            fourth:65,
            fifth:75,
            signal:'-',
            call_reset:"14",
            polivariaveis:2
        }
    }
    
]
export default buttonMenuTarget;